### ISSUE TITLE
Deprecated warning on BackBee\Utils\String

### ISSUE THREAD

**Issue by cedric-b** [backbee/BackBee#479] opened 2015-06-24 13:23 UTC
Would be good to address the deprecated issue : PHP Deprecated:  BackBee\Utils\String uses a reserved class name (String) that will break on PHP 7 and higher.
This warning pollute the php logs and the console mode (\BackBee\Standard\Application) where is displayed for every command the complete trace being quite big:

PHP Deprecated:  BackBee\Utils\String uses a reserved class name (String) that will break on PHP 7 and higher in /var/www/wlh.publishpaper.com/web/vendor/symfony/debug/DebugClassLoader.php on line 182
PHP Stack trace:
PHP   1. {main}() /var/www/wlh.publishpaper.com/web/vendor/backbee/backbee/backbee:0
PHP   2. BackBee\BBApplication->__construct() /var/www/wlh.publishpaper.com/web/vendor/backbee/backbee/backbee:23
PHP   3. BackBee\BBApplication->initEnvVariables() /var/www/wlh.publishpaper.com/web/vendor/backbee/backbee/BBApplication.php:136
PHP   4. BackBee\BBApplication->getConfig() /var/www/wlh.publishpaper.com/web/vendor/backbee/backbee/BBApplication.php:992
PHP   5. BackBee\DependencyInjection\Container->get() /var/www/wlh.publishpaper.com/web/vendor/backbee/backbee/BBApplication.php:477
PHP   6. Symfony\Component\DependencyInjection\ContainerBuilder->get() /var/www/wlh.publishpaper.com/web/vendor/backbee/backbee/DependencyInjection/Container.php:53
PHP   7. Symfony\Component\DependencyInjection\ContainerBuilder->createService() /var/www/wlh.publishpaper.com/web/vendor/symfony/dependency-injection/ContainerBuilder.php:490
PHP   8. Symfony\Component\DependencyInjection\ContainerBuilder->resolveServices() /var/www/wlh.publishpaper.com/web/vendor/symfony/dependency-injection/ContainerBuilder.php:943
PHP   9. array_map() /var/www/wlh.publishpaper.com/web/vendor/symfony/dependency-injection/ContainerBuilder.php:1015
PHP  10. Symfony\Component\DependencyInjection\ContainerBuilder->resolveServices() /var/www/wlh.publishpaper.com/web/vendor/symfony/dependency-injection/ContainerBuilder.php:1015
PHP  11. BackBee\DependencyInjection\Container->get() /var/www/wlh.publishpaper.com/web/vendor/symfony/dependency-injection/ContainerBuilder.php:1017
PHP  12. Symfony\Component\DependencyInjection\ContainerBuilder->get() /var/www/wlh.publishpaper.com/web/vendor/backbee/backbee/DependencyInjection/Container.php:53
PHP  13. Symfony\Component\DependencyInjection\ContainerBuilder->createService() /var/www/wlh.publishpaper.com/web/vendor/symfony/dependency-injection/ContainerBuilder.php:490
PHP  14. ReflectionClass->newInstanceArgs() /var/www/wlh.publishpaper.com/web/vendor/symfony/dependency-injection/ContainerBuilder.php:966
PHP  15. BackBee\Cache\File\Cache->__construct() /var/www/wlh.publishpaper.com/web/vendor/symfony/dependency-injection/ContainerBuilder.php:966
PHP  16. spl_autoload_call() /var/www/wlh.publishpaper.com/web/vendor/symfony/dependency-injection/ContainerBuilder.php:79
PHP  17. Symfony\Component\Debug\DebugClassLoader->loadClass() /var/www/wlh.publishpaper.com/web/vendor/symfony/dependency-injection/ContainerBuilder.php:79
PHP  18. trigger_error() /var/www/wlh.publishpaper.com/web/vendor/symfony/debug/DebugClassLoader.php:182

**Comment by mickaelandrieu** [comment] 2015-06-24 13:42
Hi @cedric-b,
thanks for report, it's a duplicate of https://github.com/backbee/BackBee/issues/449.

This is already fixed but not merged (see https://github.com/backbee/utils/pull/4).

**Closed by mickaelandrieu** 2015-06-24 13:42 UTC
